AMQP_URI: 'pyamqp://guest:guest@localhost'
WEB_SERVER_ADDRESS: '0.0.0.0:8000'
YOWSUP_USERNAME: !env_var '${USERNAME}'
YOWSUP_CONFIG: !env_var '${CONFIG}'
LOGIN_RESEND_MESSAGES: !env_var '${LOGIN_RESEND_MESSAGES}'
PASSWORD_RESEND_MESSAGES: !env_var '${PASSWORD_RESEND_MESSAGES}'
URL_RESEND_MESSAGES: !env_var '${URL_RESEND_MESSAGES}'
ENDPOINT_RESEND_MESSAGES: !env_var '${ENDPOINT_RESEND_MESSAGES}'
ENDPOINT_RESEND_JWT: !env_var '${ENDPOINT_RESEND_JWT}'
LOG_FILE_PATH: !env_var '${LOG_FILE_PATH}'
rpc_exchange: 'nameko-rpc'
max_workers: !env_var '${MAX_WORKERS}'
parent_calls_tracked: 10
