AMQP_URI: 'pyamqp://guest:guest@localhost'
WEB_SERVER_ADDRESS: '0.0.0.0:8000'
YOWSUP_USERNAME: !env_var '${USERNAME}'
YOWSUP_CONFIG: !env_var '${CONFIG}'
TOKEN_RESEND_MESSAGES: !env_var '${TOKEN_RESEND_MESSAGES}'
ENDPOINT_RESEND_MESSAGES: !env_var '${ENDPOINT_RESEND_MESSAGES}'
rpc_exchange: 'nameko-rpc'
max_workers: !env_var '${MAX_WORKERS}'
parent_calls_tracked: 10
